/** A single conversation turn (user message + assistant reply). */
export interface HistoryEntry {
  user: string;
  assistant: string;
  timestamp: number;
  /** Total UTF-8 byte size of user + assistant text. */
  bytes: number;
}

/**
 * Abstract memory layer — pluggable storage backend for conversation history.
 * MemoryManager orchestrates multiple layers in order.
 *
 * Current: ConversationMemoryLayer (file-based summaries).
 * Future: VectorMemoryLayer, KnowledgeBaseMemoryLayer.
 */
export abstract class IMemoryLayer {
  abstract readonly name: string;
  /** Persist a conversation turn. Called after each agent reply. */
  abstract save(chatId: string, entry: HistoryEntry): Promise<void>;
  /** Retrieve context to inject into the next prompt. */
  abstract recall(chatId: string, query?: string): Promise<string>;
  /** Receive a summary generated by the recycler. Override to persist. */
  async onSummary(_chatId: string, _date: string, _summary: string): Promise<void> {}
  /** Clean up old data (e.g. gzip files older than 30 days). */
  async cleanup(_chatId: string): Promise<void> {}
}

/**
 * Abstract memory recycler — generates summaries from ACP session files.
 * Spawns a temporary agent process to read and summarize session content.
 */
export abstract class IMemoryRecycler {
  /** Summarize a session's conversation, returning markdown text. */
  abstract summarize(chatId: string, sessionId: string): Promise<string>;
}
